name: Release Package

on:
  push:
    # branches:
    #   - main
    tags:
      - "v*"

  # release:
  #   types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun install

      - name: Build package
        run: bun run build

      - name: Rename package-name for GitHub Packages
        run: |
          jq '.name = "@amiry-jd/universal-snowflake-id"' package.json > tmp.json && mv tmp.json package.json

      - name: Configure npm for GitHub Packages
        run: |
          echo "@amiry-jd:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" >> ~/.npmrc

      - name: Check .npmrc
        run: cat ~/.npmrc

      - name: Publish to GitHub Packages
        run: |
          echo "NODE_AUTH_TOKEN is:"
          echo $NODE_AUTH_TOKEN
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Clean up .npmrc
        run: rm ~/.npmrc

      - name: Rename package-name for npm Packages
        run: |
          jq '.name = "universal-snowflake-id"' package.json > tmp.json && mv tmp.json package.json

      - name: Configure npm for npmjs packages
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: |
          echo "NODE_AUTH_TOKEN is:"
          echo $NODE_AUTH_TOKEN
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Clean up .npmrc
        run: rm ~/.npmrc
